In [6]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec
!pip install gensim

In [7]:
documents = [
    "I love natural language processing",
    "NLP is fun and interesting",
    "I love learning NLP"
]


In [8]:
count_vect = CountVectorizer()
bow_counts = count_vect.fit_transform(documents)

print("Vocabulary:", count_vect.get_feature_names_out())
print("Count Matrix:\n", bow_counts.toarray())


Vocabulary: ['and' 'fun' 'interesting' 'is' 'language' 'learning' 'love' 'natural'
 'nlp' 'processing']
Count Matrix:
 [[0 0 0 0 1 0 1 1 0 1]
 [1 1 1 1 0 0 0 0 1 0]
 [0 0 0 0 0 1 1 0 1 0]]


In [10]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import normalize

count_vect = CountVectorizer()
bow_counts = count_vect.fit_transform(documents)


In [11]:
bow_norm = normalize(bow_counts, norm='l1')

print("Normalized Count Matrix:\n", bow_norm.toarray())



Normalized Count Matrix:
 [[0.         0.         0.         0.         0.25       0.
  0.25       0.25       0.         0.25      ]
 [0.2        0.2        0.2        0.2        0.         0.
  0.         0.         0.2        0.        ]
 [0.         0.         0.         0.         0.         0.33333333
  0.33333333 0.         0.33333333 0.        ]]


In [12]:
tfidf_vect = TfidfVectorizer()
tfidf_matrix = tfidf_vect.fit_transform(documents)

print("TF-IDF Vocabulary:", tfidf_vect.get_feature_names_out())
print("TF-IDF Matrix:\n", tfidf_matrix.toarray())


TF-IDF Vocabulary: ['and' 'fun' 'interesting' 'is' 'language' 'learning' 'love' 'natural'
 'nlp' 'processing']
TF-IDF Matrix:
 [[0.         0.         0.         0.         0.52863461 0.
  0.40204024 0.52863461 0.         0.52863461]
 [0.46735098 0.46735098 0.46735098 0.46735098 0.         0.
  0.         0.         0.35543247 0.        ]
 [0.         0.         0.         0.         0.         0.68091856
  0.51785612 0.         0.51785612 0.        ]]


In [13]:
tokenized_docs = [doc.lower().split() for doc in documents]

w2v_model = Word2Vec(
    sentences=tokenized_docs,
    vector_size=100,
    window=5,
    min_count=1,
    workers=4
)


In [14]:
print("Embedding for 'nlp':\n", w2v_model.wv['nlp'])


Embedding for 'nlp':
 [-5.3622725e-04  2.3643136e-04  5.1033497e-03  9.0092728e-03
 -9.3029495e-03 -7.1168090e-03  6.4588725e-03  8.9729885e-03
 -5.0154282e-03 -3.7633716e-03  7.3805046e-03 -1.5334714e-03
 -4.5366134e-03  6.5540518e-03 -4.8601604e-03 -1.8160177e-03
  2.8765798e-03  9.9187379e-04 -8.2852151e-03 -9.4488179e-03
  7.3117660e-03  5.0702621e-03  6.7576934e-03  7.6286553e-04
  6.3508903e-03 -3.4053659e-03 -9.4640139e-04  5.7685734e-03
 -7.5216377e-03 -3.9361035e-03 -7.5115822e-03 -9.3004224e-04
  9.5381187e-03 -7.3191668e-03 -2.3337686e-03 -1.9377411e-03
  8.0774371e-03 -5.9308959e-03  4.5162440e-05 -4.7537340e-03
 -9.6035507e-03  5.0072931e-03 -8.7595852e-03 -4.3918253e-03
 -3.5099984e-05 -2.9618145e-04 -7.6612402e-03  9.6147433e-03
  4.9820580e-03  9.2331432e-03 -8.1579173e-03  4.4957981e-03
 -4.1370760e-03  8.2453608e-04  8.4986202e-03 -4.4621765e-03
  4.5175003e-03 -6.7869602e-03 -3.5484887e-03  9.3985079e-03
 -1.5776526e-03  3.2137157e-04 -4.1406299e-03 -7.6826881e-03
 -

In [15]:
print("Similar words to 'nlp':", w2v_model.wv.most_similar('nlp'))


Similar words to 'nlp': [('language', 0.21617142856121063), ('is', 0.09291722625494003), ('natural', 0.06285770982503891), ('processing', 0.027057457715272903), ('fun', 0.016134677454829216), ('love', -0.01083916611969471), ('interesting', -0.027750369161367416), ('i', -0.05234673246741295), ('and', -0.059876296669244766), ('learning', -0.111670583486557)]
